channels:
  - conda-forge
dependencies:
  - firefox
  - qgis>=3.18
  - websockify
  - pip
  - pip:
      - jupyter-remote-desktop-proxy 
      - importlib-metadata>=6.8.0 
      - distro
  - ipywidgets
  - ocl-icd-system
  - networkx
  - matplotlib
 
