channels:
  - conda-forge
dependencies:
  - qgis>=3.18
  - websockify
  - pip
  - pip:
      - jupyter-remote-desktop-proxy
      - xpresso   
      - flask==3.0.0
      - importlib-metadata==6.8.0 
  - ipywidgets
  - ocl-icd-system
 
