#!/bin/bash
set -euo pipefail
RUN useradd -ms /bin/bash linuxbrew
mkdir -p $HOME/Desktop
mkdir -p $HOME/linuxbrew/.linuxbrew

# Copy desktop files over on container start rather than on postBuild
# In JupyterHubs, $HOME in build time is not available during runtime
# as $HOME is usually a persistent directory mounted per user
cp $REPO_DIR/*.desktop $HOME/Desktop/

exec "$@"
